{% set name = "evojax" %}
{% set version = "0.2.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/evojax-{{ version }}.tar.gz
  sha256: 3a12f47fc71ceb8a7cab562ccac273c65748aaf2870f359a6c87bf0363b8b71b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - cma
    - flax
    - jax >=0.2.17
    - jaxlib >=0.1.65
    - pillow
    - python >=3.6
    - pyyaml

test:
  imports:
    - evojax
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/evojax
  summary: 'EvoJAX: Hardware-accelerated Neuroevolution.'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
